import { describe, expect, it } from 'vitest';
import { changelogIndex, ENTRIES_MARKER, withEntry } from '../src/changelog.js';

const entry = (date: string, version = '1.5') =>
  `## [${date}] — MFM v${version}\n\n**1 faction changed**\n`;

describe('withEntry (a version file)', () => {
  it('starts a new version file with a header and the entry after the marker', () => {
    const file = withEntry(undefined, '1.5', entry('2026-09-30'));
    expect(file.startsWith('# MFM v1.5\n')).toBe(true);
    expect(file).toContain('[All versions](../DATA-CHANGELOG.md)');
    expect(file).toContain(`${ENTRIES_MARKER}\n\n## [2026-09-30] — MFM v1.5\n`);
    expect(file.endsWith('**1 faction changed**\n')).toBe(true);
  });

  it('puts a later entry for the same version above the earlier one, keeping both', () => {
    const first = withEntry(undefined, '1.0', entry('2026-06-22', '1.0'));
    const both = withEntry(first, '1.0', entry('2026-06-23', '1.0'));
    expect(both.indexOf('## [2026-06-23]')).toBeLessThan(both.indexOf('## [2026-06-22]'));
    expect(both).toContain('**1 faction changed**\n\n## [2026-06-22] — MFM v1.0');
    expect(both.startsWith(first.slice(0, first.indexOf(ENTRIES_MARKER)))).toBe(true);
  });

  it('refuses a file that has lost its marker, rather than guessing where entries go', () => {
    expect(() => withEntry('# MFM v1.5\n', '1.5', entry('2026-09-30'))).toThrow(ENTRIES_MARKER);
  });
});

describe('changelogIndex (DATA-CHANGELOG.md)', () => {
  const file = (name: string, ...dates: string[]) => ({
    name,
    text: withEntry(undefined, name.slice(1, -3), dates.map((d) => entry(d)).join('\n')),
  });

  it('lists every version file newest first, comparing versions numerically', () => {
    const index = changelogIndex([
      file('v1.9.md', '2027-05-01'),
      file('v1.10.md', '2027-06-01'),
      file('v1.0.md', '2026-06-22'),
      { name: 'unversioned.md', text: '' },
    ]);
    const lines = index.split('\n').filter((l) => l.startsWith('- '));
    expect(lines).toEqual([
      '- [MFM v1.10](changelog/v1.10.md) — 2027-06-01',
      '- [MFM v1.9](changelog/v1.9.md) — 2027-05-01',
      '- [MFM v1.0](changelog/v1.0.md) — 2026-06-22',
      '- [Unversioned](changelog/unversioned.md)',
    ]);
  });

  it("lists each of a file's entry dates once, in the file's order", () => {
    const index = changelogIndex([file('v1.4.md', '2026-09-02', '2026-09-02', '2026-08-31')]);
    expect(index).toContain('- [MFM v1.4](changelog/v1.4.md) — 2026-09-02, 2026-08-31\n');
  });

  it('ignores anything in the directory that is not a version file', () => {
    const index = changelogIndex([file('v1.5.md', '2026-09-30'), { name: 'notes.txt', text: '' }]);
    expect(index).not.toContain('notes.txt');
  });

  it('opens with a header that says it is generated', () => {
    expect(changelogIndex([]).startsWith('# Data changelog\n\n<!-- Generated by')).toBe(true);
  });
});
