/**
 * The persistent changelog's files: one per MFM version under `changelog/`, indexed by
 * `DATA-CHANGELOG.md` (see *The persistent changelog* in `specs/change-tracking.md`).
 * `changelogEntry()` in `src/diff.ts` renders an entry; this places it. Pure text in,
 * text out — `scripts/update-data-changelog.ts` does the reading and writing.
 */

/** A version file's entries follow this, newest first. */
export const ENTRIES_MARKER = '<!-- BEGIN ENTRIES -->';

/** A new version file: a short header and the marker, no entries yet. */
export function versionFileHeader(version: string | undefined): string {
  const name = version ? `MFM v${version}` : 'Unversioned MFM data';
  return [
    `# ${name}`,
    '',
    `What changed in the scraped dataset with ${name}, newest entry first. Generated by the`,
    'scrape workflow (see [`specs/change-tracking.md`](../specs/change-tracking.md)); the',
    '`data/*.yaml` git history remains the canonical record. [All versions](../DATA-CHANGELOG.md)',
    '',
    ENTRIES_MARKER,
    '',
  ].join('\n');
}

/**
 * A version file with `entry` as its newest entry — `file` is the current text, or
 * `undefined` for a version that has no file yet.
 */
export function withEntry(
  file: string | undefined,
  version: string | undefined,
  entry: string,
): string {
  const text = file ?? versionFileHeader(version);
  const at = text.indexOf(ENTRIES_MARKER);
  if (at === -1) throw new Error(`changelog file is missing the "${ENTRIES_MARKER}" marker`);
  const head = text.slice(0, at + ENTRIES_MARKER.length);
  const rest = text.slice(at + ENTRIES_MARKER.length).trim();
  return `${head}\n\n${entry.trim()}\n${rest ? `\n${rest}\n` : ''}`;
}

/** A file in `changelog/`, as the index sees it: its name and its text. */
export interface VersionFile {
  name: string;
  text: string;
}

const VERSION_FILE = /^(?:v(.+)|unversioned)\.md$/;

/** Newest first, compared by numeric segment so v1.10 follows v1.9; unversioned last. */
function newestFirst(a: string | undefined, b: string | undefined): number {
  if (a === undefined || b === undefined) return a === b ? 0 : a === undefined ? 1 : -1;
  const x = a.split('.');
  const y = b.split('.');
  for (let i = 0; i < Math.max(x.length, y.length); i++) {
    const d = Number(y[i] ?? 0) - Number(x[i] ?? 0);
    if (d) return d;
  }
  return b.localeCompare(a);
}

const INDEX_HEADER = `# Data changelog

<!-- Generated by scripts/update-data-changelog.ts from changelog/ on every update: edit those, not this file. -->

All notable changes to the scraped Munitorum Field Manual dataset — one file per MFM
version under [\`changelog/\`](changelog), newest first. Generated automatically by the
scrape workflow (see [\`specs/change-tracking.md\`](specs/change-tracking.md)). The
\`data/*.yaml\` git history remains the canonical, line-level record — these are the
readable summaries.
`;

/**
 * `DATA-CHANGELOG.md`, generated whole from the version files: one line per version,
 * newest first, linking its file and listing the dates of its entries.
 */
export function changelogIndex(files: VersionFile[]): string {
  const lines = files
    .map((f) => ({ f, m: f.name.match(VERSION_FILE) }))
    .filter((x): x is { f: VersionFile; m: RegExpMatchArray } => x.m !== null)
    .sort((a, b) => newestFirst(a.m[1], b.m[1]))
    .map(({ f, m }) => {
      const dates = [...new Set([...f.text.matchAll(/^## \[([^\]]+)\]/gm)].map((d) => d[1]))];
      const name = m[1] ? `MFM v${m[1]}` : 'Unversioned';
      return `- [${name}](changelog/${f.name})${dates.length > 0 ? ` — ${dates.join(', ')}` : ''}`;
    });
  return `${INDEX_HEADER}\n${lines.join('\n')}\n`;
}
